# Generated by Django 5.1.6 on 2025-03-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='managements.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Danh sách điểm danh',
                'db_table': 'attendance',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seating', serialize=False, to='users.student')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to='managements.room')),
            ],
            options={
                'verbose_name': 'Seating',
                'verbose_name_plural': 'Seatings',
                'db_table': 'seating',
                'unique_together': {('room', 'row', 'column')},
            },
        ),
    ]
