# Generated by Django 5.1.6 on 2025-03-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Seating',
                'verbose_name_plural': 'Seatings',
                'db_table': 'seating',
                'ordering': ['room', 'row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='managements.session')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Danh sách điểm danh',
                'db_table': 'attendance',
            },
        ),
    ]
