# Generated by Django 5.1.6 on 2025-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Danh sách điểm danh',
                'db_table': 'attendance',
            },
        ),
    ]
