# Generated by Django 5.1.6 on 2025-03-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_options_alter_customuser_options_and_more'),
        ('managements', '0004_alter_session_teacher'),
        ('rooms_managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seating',
            options={'verbose_name': 'Seating', 'verbose_name_plural': 'Seatings'},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='managements.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Danh sách điểm danh',
                'db_table': 'attendance',
                'unique_together': {('student', 'session')},
            },
        ),
    ]
