# Generated by Django 5.1.6 on 2025-03-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_managements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
    ]
