# Generated by Django 5.1.6 on 2025-03-13 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All-Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('day_of_birth', models.DateField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=32, null=True)),
                ('active_status', models.CharField(blank=True, max_length=355, null=True)),
                ('contract_types', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_levels', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile-images/')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admin',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('day_of_birth', models.DateField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=32, null=True)),
                ('active_status', models.CharField(blank=True, max_length=355, null=True)),
                ('contract_types', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_levels', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile-images/')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=32, null=True)),
                ('day_of_birth', models.DateField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=32, null=True)),
                ('active_status', models.CharField(blank=True, max_length=355, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile-images/')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='managements.room')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
                'ordering': ['full_name'],
            },
        ),
    ]
