# Generated by Django 5.1.6 on 2025-03-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='room',
        ),
    ]
