# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     env_file: .env.dev
#     depends_on:
#       - db
#     volumes:
#       - .:/app
#     command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

#   db:
#     image: postgres:17
#     env_file: .env.dev
#     volumes:
#       - dev_db_data:/var/lib/postgresql/data

# volumes:
#   dev_db_data:

version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_ENV=${DJANGO_ENV}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"
