# Generated by Django 5.1.6 on 2025-03-22 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('managements', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loại tài liệu',
                'verbose_name_plural': 'Các loại tài liệu',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Thẻ',
                'verbose_name_plural': 'Thẻ tài liệu',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('public', 'Công khai'), ('restricted', 'Hạn chế')], db_index=True, default='public', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_documents', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_individual_documents', to='users.student')),
                ('rooms', models.ManyToManyField(blank=True, related_name='documents', to='managements.room')),
                ('subjects', models.ManyToManyField(blank=True, related_name='documents', to='managements.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_resources.documenttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='educational_resources.tag')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu chia sẻ',
                'db_table': 'document',
            },
        ),
    ]
