# Generated by Django 5.1.6 on 2025-04-24 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('managements', '0004_alter_room_students'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], db_index=True, default='public', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='%(class)s_allowed_documents', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='%(class)s_allowed_documents', to='users.student')),
                ('rooms', models.ManyToManyField(blank=True, related_name='%(class)s_documents', to='managements.room')),
                ('subjects', models.ManyToManyField(blank=True, related_name='%(class)s_documents', to='managements.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base Document',
                'verbose_name_plural': 'Base Documents',
                'db_table': 'base_document',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lesson Plan Status',
                'verbose_name_plural': 'Lesson Plan Statuses',
                'db_table': 'lesson_plan_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='educational_resources.basedocument')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_resources.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['-date_uploaded'],
            },
            bases=('educational_resources.basedocument',),
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('basedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='educational_resources.basedocument')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='educational_resources.lessonplanstatus')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'db_table': 'lesson_plan',
                'ordering': ['-date_uploaded'],
            },
            bases=('educational_resources.basedocument',),
        ),
        migrations.AddIndex(
            model_name='basedocument',
            index=models.Index(fields=['title'], name='base_docume_title_278cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='basedocument',
            index=models.Index(fields=['access_type'], name='base_docume_access__dff931_idx'),
        ),
        migrations.AddIndex(
            model_name='basedocument',
            index=models.Index(fields=['is_active'], name='base_docume_is_acti_805557_idx'),
        ),
        migrations.AddIndex(
            model_name='basedocument',
            index=models.Index(fields=['archived'], name='base_docume_archive_e9653f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='document_documen_0c161d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['status'], name='lesson_plan_status__2e4ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['reviewed_by'], name='lesson_plan_reviewe_2e3837_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['review_date'], name='lesson_plan_review__184fff_idx'),
        ),
    ]
