# Generated by Django 5.1.6 on 2025-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.RenameIndex(
            model_name='lessonplan',
            new_name='lesson_plan_status_5c6b64_idx',
            old_name='lesson_plan_status__2e4ba8_idx',
        ),
        migrations.DeleteModel(
            name='LessonPlanStatus',
        ),
    ]
