# Generated by Django 5.1.6 on 2025-03-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Tài liệu'},
        ),
    ]
