# Generated by Django 5.1.6 on 2025-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
