# Generated by Django 5.1.6 on 2025-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('weeks_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semester',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('lesson_number', models.IntegerField()),
                ('lesson_name', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='lesson-documents/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('absences', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'session',
                'ordering': ['day', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'db_table': 'teacher_assignment',
            },
        ),
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slot',
                'ordering': ['start_time'],
            },
        ),
    ]
