# Generated by Django 5.1.6 on 2025-02-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_time', models.PositiveIntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255)),
                ('session_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('weeks_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('absences', models.PositiveIntegerField()),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='accounts.teacher')),
                ('name_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.classtime')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.lesson')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='managements.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.semester')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='managements.subject'),
        ),
    ]
