# Generated by Django 5.1.6 on 2025-03-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='lesson_name',
        ),
    ]
