# Generated by Django 5.1.6 on 2025-02-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_id'),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTime',
            new_name='Time_slot',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='teachers',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='name_time',
            new_name='time_slot',
        ),
        migrations.RenameField(
            model_name='time_slot',
            old_name='name_time',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='classsession',
            name='day',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='absences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
