# Generated by Django 5.1.6 on 2025-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='statu',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='time_slot',
            name='id',
        ),
        migrations.AddField(
            model_name='session',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lesson-documents/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
