# Generated by Django 5.1.6 on 2025-03-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='managements.academicyear'),
        ),
        migrations.AddField(
            model_name='session',
            name='room_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='managements.room'),
        ),
        migrations.AddField(
            model_name='session',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='managements.semester'),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='managements.subject'),
        ),
        migrations.AddField(
            model_name='teacher_assignment',
            name='room_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='managements.room'),
        ),
        migrations.AddField(
            model_name='teacher_assignment',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='managements.semester'),
        ),
        migrations.AddField(
            model_name='teacher_assignment',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='managements.subject'),
        ),
        migrations.AddField(
            model_name='teacher_assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.time_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher_assignment',
            unique_together={('semester_code', 'subject_code', 'room_code', 'teacher')},
        ),
    ]
