# Generated by Django 5.1.6 on 2025-03-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['year_name'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterModelTable(
            name='academicyear',
            table='academic_year',
        ),
    ]
