# Generated by Django 5.1.6 on 2025-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='users.student'),
        ),
    ]
