# Generated by Django 5.1.6 on 2025-03-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_remove_session_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slot',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
