# Generated by Django 5.1.6 on 2025-03-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('managements', '0002_rename_statu_session_status_remove_time_slot_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['start_date'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['day', 'time_slot'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher_assignment',
            options={'verbose_name': 'Teacher Assignment', 'verbose_name_plural': 'Teacher Assignments'},
        ),
        migrations.AlterModelOptions(
            name='time_slot',
            options={'ordering': ['start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='teacher_assignment',
            unique_together={('semester_code', 'subject_code', 'room_code', 'teacher')},
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='teacher_assignment',
            table='teacher_assignment',
        ),
        migrations.AlterModelTable(
            name='time_slot',
            table='time_slot',
        ),
    ]
