# Generated by Django 5.1.6 on 2025-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_alter_academicyear_options_alter_academicyear_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
