# Generated by Django 5.1.6 on 2025-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_alter_room_students'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='users.student'),
        ),
    ]
