# Generated by Django 5.1.6 on 2025-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_remove_time_slot_id_subject_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='statu',
            new_name='status',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
