# Generated by Django 5.1.6 on 2025-03-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_options_alter_customuser_options_and_more'),
        ('managements', '0003_alter_room_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.teacher'),
        ),
    ]
