# Generated by Django 5.1.6 on 2025-03-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_session_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='room_code',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='teacher_assignment',
            old_name='room_code',
            new_name='room_id',
        ),
        migrations.AlterUniqueTogether(
            name='teacher_assignment',
            unique_together={('semester_code', 'subject_code', 'room_id', 'teacher')},
        ),
    ]
