# Generated by Django 5.1.6 on 2025-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_session_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='managements.semester'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
