# Generated by Django 5.1.6 on 2025-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_rename_statu_session_status_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
