# Generated by Django 5.1.6 on 2025-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_room_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='lesson_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='lesson_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
